- name: download tomcat binary
  get_url:
    url: {{ tomcat_download_url }}
    dest: /usr/src/tomcat-{{ version }}.tar.gz
    checksum: sha256:{{ tomcat_sha256_url }}
  tags: ['tomcat']

- name: extract tomcat to tomcat_home
  unarchive:
    src: /usr/src/tomcat-{{ version }}.tar.gz
    dest: {{ tomcat_catalina_install_dir }}
  tags: ['tomcat']

- name: remove noisy files
  file:
    path: {{ tomcat_catalina_home }}/{{ item }}
    state: absent
  with_items:
    - logs
    - work
    - temp
    - bin/*.bat
    - NOTICE
    - RELEASE-NOTES
    - RUNNING.txt
  tags: ['tomcat']

- name: rename conf dir
  command:
    mv {{ tomcat_catalina_home }}/conf {{ tomcat_catalina_home }}/conf.dist
  tags: ['tomcat']

- name: ensure tomcat is enabled
  service: name=tomcat enabled=yes
  tags: ['tomcat']