---
name: Molecule Test

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: molecule
        uses: robertdebock/molecule-action@2.0.0
        with:
          entrypoint: /usr/local/bin/molecule
          args: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "centos"
            tag: "6"
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "8"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.0.0
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          options: "--parallel all"